/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { JosephusTaskLoadingState } from "./components/josephus-task/josephus-task";
export { JosephusTaskLoadingState } from "./components/josephus-task/josephus-task";
export namespace Components {
    interface JosephusAudio {
        "midi": string;
    }
    interface JosephusBaseComponent {
    }
    interface JosephusChallenge {
        "spec": ChallengeSpec | undefined;
    }
    interface JosephusExam {
        "href"?: string;
    }
    interface JosephusField {
        /**
          * @default []
         */
        "scores": StringMEI[][];
        "spec": FieldSpec | undefined;
    }
    interface JosephusSnippet {
        "data": string | null;
        "href": string | null;
        /**
          * @default ['label', 'audio', 'score']
         */
        "repr": ScoreRepr[];
    }
    interface JosephusTask {
        /**
          * @default 0
         */
        "count": number;
        "spec": TaskSpec | undefined;
    }
    interface JosephusTimer {
        /**
          * @default this.debug ? 5 : 0
         */
        "danger": number;
        /**
          * @default true
         */
        "debug": boolean;
        /**
          * @default this.debug ? 2 : 0
         */
        "overrun": number;
        /**
          * @default "Time's up!"
         */
        "overrunText": string;
        /**
          * @readonly 
          * @default false
         */
        "paused": boolean;
        /**
          * @readonly
         */
        "runs": boolean;
        /**
          * @default this.debug ? 10 : 60
         */
        "secs": number;
        /**
          * @readonly
         */
        "started": boolean;
        /**
          * @readonly 
          * @default null
         */
        "state": JosephusTimerState | null;
        /**
          * @default this.debug ? 3 : 0
         */
        "warmup": number;
    }
}
export interface JosephusTaskCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJosephusTaskElement;
}
export interface JosephusTimerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJosephusTimerElement;
}
declare global {
    interface HTMLJosephusAudioElement extends Components.JosephusAudio, HTMLStencilElement {
    }
    var HTMLJosephusAudioElement: {
        prototype: HTMLJosephusAudioElement;
        new (): HTMLJosephusAudioElement;
    };
    interface HTMLJosephusBaseComponentElement extends Components.JosephusBaseComponent, HTMLStencilElement {
    }
    var HTMLJosephusBaseComponentElement: {
        prototype: HTMLJosephusBaseComponentElement;
        new (): HTMLJosephusBaseComponentElement;
    };
    interface HTMLJosephusChallengeElement extends Components.JosephusChallenge, HTMLStencilElement {
    }
    var HTMLJosephusChallengeElement: {
        prototype: HTMLJosephusChallengeElement;
        new (): HTMLJosephusChallengeElement;
    };
    interface HTMLJosephusExamElement extends Components.JosephusExam, HTMLStencilElement {
    }
    var HTMLJosephusExamElement: {
        prototype: HTMLJosephusExamElement;
        new (): HTMLJosephusExamElement;
    };
    interface HTMLJosephusFieldElement extends Components.JosephusField, HTMLStencilElement {
    }
    var HTMLJosephusFieldElement: {
        prototype: HTMLJosephusFieldElement;
        new (): HTMLJosephusFieldElement;
    };
    interface HTMLJosephusSnippetElement extends Components.JosephusSnippet, HTMLStencilElement {
    }
    var HTMLJosephusSnippetElement: {
        prototype: HTMLJosephusSnippetElement;
        new (): HTMLJosephusSnippetElement;
    };
    interface HTMLJosephusTaskElementEventMap {
        "josephus-task-loading": { state: JosephusTaskLoadingState };
    }
    interface HTMLJosephusTaskElement extends Components.JosephusTask, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJosephusTaskElementEventMap>(type: K, listener: (this: HTMLJosephusTaskElement, ev: JosephusTaskCustomEvent<HTMLJosephusTaskElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJosephusTaskElementEventMap>(type: K, listener: (this: HTMLJosephusTaskElement, ev: JosephusTaskCustomEvent<HTMLJosephusTaskElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJosephusTaskElement: {
        prototype: HTMLJosephusTaskElement;
        new (): HTMLJosephusTaskElement;
    };
    interface HTMLJosephusTimerElementEventMap {
        "josephus-timer-state-changed": { state: JosephusTimerState | null };
        "josephus-timer-progress": any;
    }
    interface HTMLJosephusTimerElement extends Components.JosephusTimer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJosephusTimerElementEventMap>(type: K, listener: (this: HTMLJosephusTimerElement, ev: JosephusTimerCustomEvent<HTMLJosephusTimerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJosephusTimerElementEventMap>(type: K, listener: (this: HTMLJosephusTimerElement, ev: JosephusTimerCustomEvent<HTMLJosephusTimerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJosephusTimerElement: {
        prototype: HTMLJosephusTimerElement;
        new (): HTMLJosephusTimerElement;
    };
    interface HTMLElementTagNameMap {
        "josephus-audio": HTMLJosephusAudioElement;
        "josephus-base-component": HTMLJosephusBaseComponentElement;
        "josephus-challenge": HTMLJosephusChallengeElement;
        "josephus-exam": HTMLJosephusExamElement;
        "josephus-field": HTMLJosephusFieldElement;
        "josephus-snippet": HTMLJosephusSnippetElement;
        "josephus-task": HTMLJosephusTaskElement;
        "josephus-timer": HTMLJosephusTimerElement;
    }
}
declare namespace LocalJSX {
    interface JosephusAudio {
        "midi"?: string;
    }
    interface JosephusBaseComponent {
    }
    interface JosephusChallenge {
        "spec"?: ChallengeSpec | undefined;
    }
    interface JosephusExam {
        "href"?: string;
    }
    interface JosephusField {
        /**
          * @default []
         */
        "scores"?: StringMEI[][];
        "spec"?: FieldSpec | undefined;
    }
    interface JosephusSnippet {
        "data"?: string | null;
        "href"?: string | null;
        /**
          * @default ['label', 'audio', 'score']
         */
        "repr"?: ScoreRepr[];
    }
    interface JosephusTask {
        /**
          * @default 0
         */
        "count"?: number;
        "onJosephus-task-loading"?: (event: JosephusTaskCustomEvent<{ state: JosephusTaskLoadingState }>) => void;
        "spec"?: TaskSpec | undefined;
    }
    interface JosephusTimer {
        /**
          * @default this.debug ? 5 : 0
         */
        "danger"?: number;
        /**
          * @default true
         */
        "debug"?: boolean;
        "onJosephus-timer-progress"?: (event: JosephusTimerCustomEvent<any>) => void;
        "onJosephus-timer-state-changed"?: (event: JosephusTimerCustomEvent<{ state: JosephusTimerState | null }>) => void;
        /**
          * @default this.debug ? 2 : 0
         */
        "overrun"?: number;
        /**
          * @default "Time's up!"
         */
        "overrunText"?: string;
        /**
          * @readonly 
          * @default false
         */
        "paused"?: boolean;
        /**
          * @readonly
         */
        "runs"?: boolean;
        /**
          * @default this.debug ? 10 : 60
         */
        "secs"?: number;
        /**
          * @readonly
         */
        "started"?: boolean;
        /**
          * @readonly 
          * @default null
         */
        "state"?: JosephusTimerState | null;
        /**
          * @default this.debug ? 3 : 0
         */
        "warmup"?: number;
    }

    interface JosephusAudioAttributes {
        "midi": string;
    }
    interface JosephusExamAttributes {
        "href": string;
    }
    interface JosephusSnippetAttributes {
        "href": string | null;
        "data": string | null;
    }
    interface JosephusTaskAttributes {
        "count": number;
    }
    interface JosephusTimerAttributes {
        "debug": boolean;
        "secs": number;
        "warmup": number;
        "danger": number;
        "overrun": number;
        "overrunText": string;
        "state": JosephusTimerState | null;
        "started": boolean;
        "paused": boolean;
        "runs": boolean;
    }

    interface IntrinsicElements {
        "josephus-audio": Omit<JosephusAudio, keyof JosephusAudioAttributes> & { [K in keyof JosephusAudio & keyof JosephusAudioAttributes]?: JosephusAudio[K] } & { [K in keyof JosephusAudio & keyof JosephusAudioAttributes as `attr:${K}`]?: JosephusAudioAttributes[K] } & { [K in keyof JosephusAudio & keyof JosephusAudioAttributes as `prop:${K}`]?: JosephusAudio[K] };
        "josephus-base-component": JosephusBaseComponent;
        "josephus-challenge": JosephusChallenge;
        "josephus-exam": Omit<JosephusExam, keyof JosephusExamAttributes> & { [K in keyof JosephusExam & keyof JosephusExamAttributes]?: JosephusExam[K] } & { [K in keyof JosephusExam & keyof JosephusExamAttributes as `attr:${K}`]?: JosephusExamAttributes[K] } & { [K in keyof JosephusExam & keyof JosephusExamAttributes as `prop:${K}`]?: JosephusExam[K] };
        "josephus-field": JosephusField;
        "josephus-snippet": Omit<JosephusSnippet, keyof JosephusSnippetAttributes> & { [K in keyof JosephusSnippet & keyof JosephusSnippetAttributes]?: JosephusSnippet[K] } & { [K in keyof JosephusSnippet & keyof JosephusSnippetAttributes as `attr:${K}`]?: JosephusSnippetAttributes[K] } & { [K in keyof JosephusSnippet & keyof JosephusSnippetAttributes as `prop:${K}`]?: JosephusSnippet[K] };
        "josephus-task": Omit<JosephusTask, keyof JosephusTaskAttributes> & { [K in keyof JosephusTask & keyof JosephusTaskAttributes]?: JosephusTask[K] } & { [K in keyof JosephusTask & keyof JosephusTaskAttributes as `attr:${K}`]?: JosephusTaskAttributes[K] } & { [K in keyof JosephusTask & keyof JosephusTaskAttributes as `prop:${K}`]?: JosephusTask[K] };
        "josephus-timer": Omit<JosephusTimer, keyof JosephusTimerAttributes> & { [K in keyof JosephusTimer & keyof JosephusTimerAttributes]?: JosephusTimer[K] } & { [K in keyof JosephusTimer & keyof JosephusTimerAttributes as `attr:${K}`]?: JosephusTimerAttributes[K] } & { [K in keyof JosephusTimer & keyof JosephusTimerAttributes as `prop:${K}`]?: JosephusTimer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "josephus-audio": LocalJSX.IntrinsicElements["josephus-audio"] & JSXBase.HTMLAttributes<HTMLJosephusAudioElement>;
            "josephus-base-component": LocalJSX.IntrinsicElements["josephus-base-component"] & JSXBase.HTMLAttributes<HTMLJosephusBaseComponentElement>;
            "josephus-challenge": LocalJSX.IntrinsicElements["josephus-challenge"] & JSXBase.HTMLAttributes<HTMLJosephusChallengeElement>;
            "josephus-exam": LocalJSX.IntrinsicElements["josephus-exam"] & JSXBase.HTMLAttributes<HTMLJosephusExamElement>;
            "josephus-field": LocalJSX.IntrinsicElements["josephus-field"] & JSXBase.HTMLAttributes<HTMLJosephusFieldElement>;
            "josephus-snippet": LocalJSX.IntrinsicElements["josephus-snippet"] & JSXBase.HTMLAttributes<HTMLJosephusSnippetElement>;
            "josephus-task": LocalJSX.IntrinsicElements["josephus-task"] & JSXBase.HTMLAttributes<HTMLJosephusTaskElement>;
            "josephus-timer": LocalJSX.IntrinsicElements["josephus-timer"] & JSXBase.HTMLAttributes<HTMLJosephusTimerElement>;
        }
    }
}
