/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ScoreRepr } from "./components/josephus-task/josephus-task";
export { ScoreRepr } from "./components/josephus-task/josephus-task";
export namespace Components {
    interface JosephusSnippet {
        "data": string | null;
        "href": string | null;
        /**
          * @default ['label', 'audio', 'score']
         */
        "repr": ScoreRepr[];
    }
    interface JosephusTask {
        "loadData": (spec?: TaskSpec) => Promise<void>;
    }
    interface JosephusTimer {
        /**
          * @default this.debug ? 5 : 0
         */
        "danger": number;
        /**
          * @default true
         */
        "debug": boolean;
        /**
          * @default this.debug ? 2 : 0
         */
        "overrun": number;
        /**
          * @default "Time's up!"
         */
        "overrunText": string;
        /**
          * @readonly 
          * @default false
         */
        "paused": boolean;
        /**
          * @readonly
         */
        "runs": boolean;
        /**
          * @default this.debug ? 10 : 60
         */
        "secs": number;
        /**
          * @readonly
         */
        "started": boolean;
        /**
          * @readonly 
          * @default null
         */
        "state": JosephusTimerState | null;
        /**
          * @default this.debug ? 3 : 0
         */
        "warmup": number;
    }
    interface JosephusVerovioComponent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
}
export interface JosephusTimerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJosephusTimerElement;
}
declare global {
    interface HTMLJosephusSnippetElement extends Components.JosephusSnippet, HTMLStencilElement {
    }
    var HTMLJosephusSnippetElement: {
        prototype: HTMLJosephusSnippetElement;
        new (): HTMLJosephusSnippetElement;
    };
    interface HTMLJosephusTaskElement extends Components.JosephusTask, HTMLStencilElement {
    }
    var HTMLJosephusTaskElement: {
        prototype: HTMLJosephusTaskElement;
        new (): HTMLJosephusTaskElement;
    };
    interface HTMLJosephusTimerElementEventMap {
        "josephus-timer-state-changed": { state: JosephusTimerState | null };
        "josephus-timer-progress": { progress: JosephusTimerProgress };
    }
    interface HTMLJosephusTimerElement extends Components.JosephusTimer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJosephusTimerElementEventMap>(type: K, listener: (this: HTMLJosephusTimerElement, ev: JosephusTimerCustomEvent<HTMLJosephusTimerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJosephusTimerElementEventMap>(type: K, listener: (this: HTMLJosephusTimerElement, ev: JosephusTimerCustomEvent<HTMLJosephusTimerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJosephusTimerElement: {
        prototype: HTMLJosephusTimerElement;
        new (): HTMLJosephusTimerElement;
    };
    interface HTMLJosephusVerovioComponentElement extends Components.JosephusVerovioComponent, HTMLStencilElement {
    }
    var HTMLJosephusVerovioComponentElement: {
        prototype: HTMLJosephusVerovioComponentElement;
        new (): HTMLJosephusVerovioComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "josephus-snippet": HTMLJosephusSnippetElement;
        "josephus-task": HTMLJosephusTaskElement;
        "josephus-timer": HTMLJosephusTimerElement;
        "josephus-verovio-component": HTMLJosephusVerovioComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JosephusSnippet {
        "data"?: string | null;
        "href"?: string | null;
        /**
          * @default ['label', 'audio', 'score']
         */
        "repr"?: ScoreRepr[];
    }
    interface JosephusTask {
    }
    interface JosephusTimer {
        /**
          * @default this.debug ? 5 : 0
         */
        "danger"?: number;
        /**
          * @default true
         */
        "debug"?: boolean;
        "onJosephus-timer-progress"?: (event: JosephusTimerCustomEvent<{ progress: JosephusTimerProgress }>) => void;
        "onJosephus-timer-state-changed"?: (event: JosephusTimerCustomEvent<{ state: JosephusTimerState | null }>) => void;
        /**
          * @default this.debug ? 2 : 0
         */
        "overrun"?: number;
        /**
          * @default "Time's up!"
         */
        "overrunText"?: string;
        /**
          * @readonly 
          * @default false
         */
        "paused"?: boolean;
        /**
          * @readonly
         */
        "runs"?: boolean;
        /**
          * @default this.debug ? 10 : 60
         */
        "secs"?: number;
        /**
          * @readonly
         */
        "started"?: boolean;
        /**
          * @readonly 
          * @default null
         */
        "state"?: JosephusTimerState | null;
        /**
          * @default this.debug ? 3 : 0
         */
        "warmup"?: number;
    }
    interface JosephusVerovioComponent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface JosephusSnippetAttributes {
        "href": string | null;
        "data": string | null;
    }
    interface JosephusTimerAttributes {
        "debug": boolean;
        "secs": number;
        "warmup": number;
        "danger": number;
        "overrun": number;
        "overrunText": string;
        "state": JosephusTimerState | null;
        "started": boolean;
        "paused": boolean;
        "runs": boolean;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "josephus-snippet": Omit<JosephusSnippet, keyof JosephusSnippetAttributes> & { [K in keyof JosephusSnippet & keyof JosephusSnippetAttributes]?: JosephusSnippet[K] } & { [K in keyof JosephusSnippet & keyof JosephusSnippetAttributes as `attr:${K}`]?: JosephusSnippetAttributes[K] } & { [K in keyof JosephusSnippet & keyof JosephusSnippetAttributes as `prop:${K}`]?: JosephusSnippet[K] };
        "josephus-task": JosephusTask;
        "josephus-timer": Omit<JosephusTimer, keyof JosephusTimerAttributes> & { [K in keyof JosephusTimer & keyof JosephusTimerAttributes]?: JosephusTimer[K] } & { [K in keyof JosephusTimer & keyof JosephusTimerAttributes as `attr:${K}`]?: JosephusTimerAttributes[K] } & { [K in keyof JosephusTimer & keyof JosephusTimerAttributes as `prop:${K}`]?: JosephusTimer[K] };
        "josephus-verovio-component": JosephusVerovioComponent;
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "josephus-snippet": LocalJSX.IntrinsicElements["josephus-snippet"] & JSXBase.HTMLAttributes<HTMLJosephusSnippetElement>;
            "josephus-task": LocalJSX.IntrinsicElements["josephus-task"] & JSXBase.HTMLAttributes<HTMLJosephusTaskElement>;
            "josephus-timer": LocalJSX.IntrinsicElements["josephus-timer"] & JSXBase.HTMLAttributes<HTMLJosephusTimerElement>;
            "josephus-verovio-component": LocalJSX.IntrinsicElements["josephus-verovio-component"] & JSXBase.HTMLAttributes<HTMLJosephusVerovioComponentElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
